In [2]:
import numpy as np

arr = np.array([2,3,6,4,])
np.save('outfile',arr)
print(arr.ndim)

1


In [10]:
ar = np.load("outfile.npy")
ar[[2,1]]

array([6, 3])

In [4]:
mrr = np.arange(12).reshape(2,2,3)
print(mrr)
print(mrr[:1,:1])
print(mrr[:1,0:,:1])


[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[0 1 2]]]
[[[0]
  [3]]]


In [6]:
import pandas as pd

In [14]:
ser = np.arange(12).reshape(4,3)
res = pd.DataFrame(ser,index=['a','b','c','d'])
res

0   1   2
a  0   1   2
b  3   4   5
c  6   7   8
d  9  10  11

In [16]:
marks = pd.DataFrame({"physic":[45,56,23],
                      "maths":[45,35,98],
                      "chemistry":[58,97,89]
},index=["dev","aniket","amit"])
marks

physic  maths  chemistry
dev         45     45         58
aniket      56     35         97
amit        23     98         89

In [19]:
marks.reindex(["a","b","c"],fill_value = 100)

physic  maths  chemistry
dev         45     45         58
aniket      56     35         97
amit        23     98         89

In [33]:
unsort_df = pd.DataFrame(np.arange(50).reshape(10,5),index=[7,1,8,9,4,5,6,0,2,3],columns=["col1","col2","col3","col4","col5"])
print(unsort_df)
sorted_df = unsort_df.sort_index(axis=0)
sorted_df

   col1  col2  col3  col4  col5
7     0     1     2     3     4
1     5     6     7     8     9
8    10    11    12    13    14
9    15    16    17    18    19
4    20    21    22    23    24
5    25    26    27    28    29
6    30    31    32    33    34
0    35    36    37    38    39
2    40    41    42    43    44
3    45    46    47    48    49


col1  col2  col3  col4  col5
0    35    36    37    38    39
1     5     6     7     8     9
2    40    41    42    43    44
3    45    46    47    48    49
4    20    21    22    23    24
5    25    26    27    28    29
6    30    31    32    33    34
7     0     1     2     3     4
8    10    11    12    13    14
9    15    16    17    18    19